### ISSUE TITLE
Provide notifications when actions were taken

### ISSUE THREAD

**Issue by boombatower** [steamtricks/steamtricks#10]
Certainly have a setting and perhaps off by default, but it would be nice to know when cleanup was performed (and found something).

**Comment by moozaad** [comment]
Simple implementation with notify-send or libnotify? Certainly also keep a log.

Have to be aware of notification popups possibly causing issues with compositors or not being shown at all if a game was fixed and launched quickly.

Would a system tray app be worth considering for a later milestone?

**Comment by boombatower** [comment]
System tray app has some potential. If we support installing dependencies via distro packages a user prompt for sudo will be necessary with something like `ksudo` and the like (did they replace that recently?). The log is good, I know sending notifications is fairly easy, but I imagine we may need >1 implementation as if I remember ubuntu/gnome/kde all have a different standard that semi inter-operate.

**Comment by boombatower** [comment]
```
notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information
```

seems to work on plasma 5 and I believe is the libnotify cli tool so we can start there.

Presumably the actions that could be notification worthy so far are:

- detect app update/install
- steam_library_directories_clean() called
- steam_library_directories_clean() actually did something

The last one being of the most interest.

**Comment by boombatower** [comment]
Something along the lines of:

```
diff --git a/src/steamtricks b/src/steamtricks
index 6d7cced..128f2c9 100755
--- a/src/steamtricks
+++ b/src/steamtricks
@@ -13,6 +13,14 @@ STEAM_OPENSSL_REPLACE=0
 # run-time constants
 STEAM_DIR=~/.local/share/Steam
 STEAM_RUNTIME=$STEAM_DIR/ubuntu12_32/steam-runtime
+NOTIFICATION=1
+
+log()
+{
+  if test "$NOTIFICATION" == 1 ; then
+    notify-send "steamtricks" "$1" --icon=dialog-information
+  fi
+}
 
 strip_quotes()
 {
@@ -50,7 +58,10 @@ steam_library_directories_clean()
   echo "removing troublesome libraries..."
   for dir in "${directories[@]}"; do
     echo "-> checking $dir"
-    find "$dir" -type f -name "libstdc*" -print -delete
+    local count=$(find "$dir" -type f -name "libstdc*" -print -delete | wc -l)
+    if [[ $count -gt 0 ]] ; then
+      log "$count troublesome file(s) removed"
+    fi
   done
 }
 ```

Not sure what level of granularity for controlling them. For now this will probably be the only one and there is no config file. The script already spits out some information that gets mixed into steam log when started with steam. That can either be redirected to a separate log file or a log() function can be used to send specific things to that file.

**Comment by boombatower** [comment]
Initial implementation committed. Pull requests to change further.
