### ISSUE TITLE
Preference on license?

### ISSUE THREAD

**Issue by boombatower** [steamtricks/steamtricks#14]
For the reasons Linux states GPL v2 over v3 or perhaps unlicense? Also is it required to commit it to the repo or can it just be stated in README? I always fine it ugly to commit identical license text that is hosted elsewhere.

**Comment by moozaad** [comment]
Happy with GPL2. I would certainly add COPYING and, CREDIT or AUTHORS to the repo.

**Comment by boombatower** [comment]
Went with GPLv2 with note like kernel. We can always revisit.
