### ISSUE TITLE
Determine how steam knows what to execute or steamdb what are executables

### ISSUE THREAD

**Issue by boombatower** [steamtricks/steamtricks#21]
See comment in code, but find is set to look one directory deep for performance. Dota 2 breaks that as nothing is in root directory. If this ends up being more common either it will need to search deeper, or such games will need a file specifying the executable to look at, or a better automated method.

Searching deeper is slow since many games ship big data files and such that the rpm tool then has to look at.

**Comment by moozaad** [comment]
filter by +x ? Looking at fileattr first is a lot quickly that 'file' all the directories.` find -executable` ?

**Comment by boombatower** [comment]
Yeah, that'd be nice, but unfortunately steam makes every single file inside an app directory executable. ;) I should probably file a bug, but the reason is probably that steam doesn't know which files need to be executable and they do not have a mechanism for specifying such information about files since they never needed on windows. As such it highly unlikely it will change anytime soon.

**Comment by moozaad** [comment]
Could we write a curl to get the info from steam's servers like steamdb does?  https://steamdb.info/app/346110/config/

**Comment by boombatower** [comment]
Sounds good, that information isn't present on disk somewhere? The local steam client obviously knows what to execute. It would definitely be preferable to have steam tell steamtricks what to look at.

**Comment by moozaad** [comment]
They're in binary format in depotcache/*.manifest. Ark has 3 files totalling 12MB of manifests. Maybe worth investigating this tool to check the info in them https://github.com/leovp/steamfiles

**Comment by boombatower** [comment]
The more I think about this I am not sure reading that information will help. If anything it will return a bash startup script for most games which invokes an executable. Reading the executable even isn't necessarily correct since they ship with `.so` files that should be read as well. It will probably have to remain a file scan. It would be somewhat preferable to be able to scan all the games ahead of time since it can take a while to let it scan everything, but then we'd have to maintain that too. If only Valve shipped rpms  :)

The other consideration that I ignored for the time being was that many games ship 32bit and 64bit versions of the game and the current tool will try and install deps for both. It wouldn't be too hard to read the elf class on executables and libs and ignore is not equal to running arch if that arch is available...otherwise if only 32bit then install its deps. Probably better to focus on that. The only question is what to do about it taking a while to run, should it let the user know it's checking or what.

**Comment by boombatower** [comment]
One potential speed up would be to read update logs if they are specific about which files are updated (verify does) and only check those for deps, but that would probably require caching on a file level. Most games it's relatively quick, but for something like dota2 it's rather slow. Another thought, if cached don't check by default and provide a mechanism to force another check.

The second option is probably the best since most released games are not going to change deps much, but short of a command line option there is no quick way to allow force. Perhaps on verify action assume user wants things to be fixed (for now)?

To compare I wrote a regex to get `.so` files and those with no extension (best I could do consistently is no period in the name at all).
```
.*/((.+(\.so(\.[0-9]+)?))|([^.]+))$
```

```
real    1m23.073s
user    0m32.080s
sys     0m34.652s
```

with naive approach (all files) [stopped before it even finished provides]:
```
real    6m55.905s
user    0m0.016s
sys     0m0.004s
```

dota2 is probably just about the worst case with >4800 files compared to many other games < 50.

**Comment by boombatower** [comment]
I added another cache layer (c2027cdcbca9c4436efab1eed02e54ec21dcf584) to avoid processing binaries whenever possible. This will have to do for the time being. It seems rather complete anyway.
