### ISSUE TITLE
daemon name

### ISSUE THREAD

**Issue by moozaad** [steamtricks/steamtricks#24]
Daemon should have it's own name instead of bash

Try calling the daemon with. Not tested

`exec -a steamtricks-daemon steamtricks --watch`

that man page is awful but that looks about right.

**Comment by boombatower** [comment]
A name would definitely be nice as it makes it easier to identify in process lists and what not.

Perhaps, as is common, `steamtricksd`?

**Comment by boombatower** [comment]
`exec -a steamtricksd ./src/steamtricks --watch`

Still shows as bash as one would expect, not sure what the name is used for.
```
boombat+ 11159  0.0  0.0  13612   596 pts/3    S+   17:10   0:00 bash /home/boombatower/software/steamtricks/src/steamtricks --watch
```

WIth systemd user service I do not think this is really an issue. Name the systemd service file `steamtrickd` thought.

**Comment by moozaad** [comment]
Could we write a curl to get the info from steam's servers like steamdb does?  https://steamdb.info/app/346110/config/
