### ISSUE TITLE
[Suggestion] Battleblock Theater [Mesa Crash Fix]

### ISSUE THREAD

**Issue by XenonPK** [steamtricks/steamtricks#39]
Battleblock Theater crashes on startup using mesa. I found a fix in the steam community forums and created a binary patch that I uploaded to [pcgamingwiki](http://pcgamingwiki.com/w/index.php?title=BattleBlock_Theater#Linux_version_crashes_on_startup_when_using_mesa) for better visibility.
However, (Tumbleweed user here) the idea of automating the process so that users don't have to deal with it is much more interesting.
I know steamtricks is intended to fix steam runtime issues, however, would there be room for something like this?

**Comment by boombatower** [comment]
Certainly, steamtricks is also intended to fix game issues. See steamtricks-data for app specific fixes and https://github.com/steamtricks/steamtricks/wiki for an explanation on how to create them.

**Comment by XenonPK** [comment]
Is there a way of limiting the patch to the current version of the game? Since it's a binary patch, it might not work with updates.
Also, to apply the patch, the bsdiff package is required (it contains bspatch), the user might not have it installed, Is there a good way around that?
Installing dependencies required by the script itself?

**Comment by boombatower** [comment]
We can add as a dep to steamtricks-data as I imagine it is probably useful for other games.

**Comment by boombatower** [comment]
Will then need to either come up with naming scheme or something so streamtricks knows to use bspatch or if not worth it we can just use a 00-pre script to apply it. Seems like it might be cleaner to support it with a name like `.patch.bspatch` or somesuch.

**Comment by boombatower** [comment]
Looking at it some more it does not seem to the patches include what files to patch and what not so for now should probably just use a script to apply it, but need to name something other than `.diff|.patch` to ensure not applied as normal patch. Also not sure if git apply binary can handle it.

**Comment by XenonPK** [comment]
https://git-scm.com/docs/git-apply look at the --binary option.
The description seems to suggest binary patches are supported?
I'll try the script first, and change the file extension.

**Comment by boombatower** [comment]
Alright, let me know if you have trouble or find the wiki lacking. `.bspatch` is probably fine.

**Comment by XenonPK** [comment]
> #!/usr/bin/env bash
bspatch BattleBlockTheater BattleBlockTheater_patched mesa.bspatch
mv BattleBlockTheater_patched BattleBlockTheater
chmod +x BattleBlockTheater

So the script looks something like this. The question is , under what working directory will it execute, and can it find the bspatch file?
Does it run under the game's install dir?

**Comment by boombatower** [comment]
Yes, it executes in game's install directory. The script location should still be next to patch (which I think you did in your PR).

**Comment by XenonPK** [comment]
Yes, I tested it, and it applied the patch without any issues. For this to work all that is needed is to add the bsdiff package as a dependency in OBS :+1:

**Comment by boombatower** [comment]
I noted that it applies the change properly from logs, but the notification is wrong and so no changes.

I corrected in 41bd88ae70f8b0f9798f08fbf399c10ab8589f9a. I'll update steamtricks-data to require bsdiff package.

**Comment by XenonPK** [comment]
Yes, I completely forgot to mention that it did not display the notification when it applied the patch.

**Comment by boombatower** [comment]
Accepted the pull request and this fix. I'll update the packages shortly.

**Comment by boombatower** [comment]
It might be a good idea to comment pack in the forum thread since there was even a comment about each update undoing the change...as steamtricks solves that with your PR. :)

**Comment by boombatower** [comment]
Not sure if https://steamcommunity.com/app/238460/discussions/1/451848855012217196/?ctp=3#c133256240730773507 would be a better way since it does not require the binary patching tool. Something to consider going forward if we have to do more like this.

**Comment by XenonPK** [comment]
I just saw that too, I guess it would depend on how big the binary patch is.
