### ISSUE TITLE
Flesh out the dependency resolution system

### ISSUE THREAD

**Issue by boombatower** [steamtricks/steamtricks#4]
There are a few tools to resolving dependencies to distro packages (pkgconfig and the like) and some other projects that may tackle this as well (like playonlinux). Lets evaluate some solutions and come up with a way for listing missing dependencies for games in the least distro specific way that is pratical.

**Comment by moozaad** [comment]
In addition to deps, do we also include fixes to start up scripts included with games? We would need a database based on appid with deps to check and install, and global fixes and distrib specific fixes within that. And/or completely override how the game is launched if necessary with very broken titles.

Should the latest DB be automatically fetched from GH/CDN or rely on distrib maintainers to fetch?

Do we need to rely on distrib specific package tools to find deps or have the fixes DB community created with a list of packages needed per title per distrib?

**Comment by boombatower** [comment]
That's a good point and it would definitely increase speed to get fixes out if it was downloaded by client rather than shipped with package. The fixes to startup scripts is another good point since I've had to fix scripts that do not detect 64bit properly and imagine far more things.

perhaps a simple directory structure based on appid and then one for global fixes.
```
base/
- patches to steam startup script shipped with distro (like one that already in repo)
runtime/
- patches relative to steam runetime (probably not needed)
steamapp/
- patches relative to steamapp directories (library entries)
$appid/
- patches relative to appid base directory
```

Perhaps the option for a script in any directory to run anytime that thing is updated or started. The big question is dependency resolution. It would seem that for the most part that ought to be automatic. ldd tells us what is missing and simply need expected dependency versions in a file for each app and a way to translate them to distro packages.

There was the "maintainer tool" mentioned in factory mailing list a while back that did something of that sort.

Perhaps to avoid more initial work we can just ship to fixes with the package and worry about downloading/updating it on the fly later?

**Comment by moozaad** [comment]
I like the directory structure idea for a database. Certainly simpler than sqllite or xml.

Looking at your listing I presume that would be distrib specific, saves DL'ing unnecessary fixes but the top level for devs would be broken up distribs.

Fixes would also have to be tied to versions of the title/appid. As in cases with where there's actual linux support, they may publish fixes incompatible with our fixes... and also we'd need to support branches for where games use the 'beta' function to freeze the version (see factorio & project zomboid for examples).


eg.

```
Leap/
-base/
-- patches to steam startup script shipped with distro (like one that already in repo)
-runtime/
-- patches relative to steam runetime (probably not needed)
-steamapp/
-- patches relative to steamapp directories (library entries)
-$appid/
-- patches relative to appid base directory
-----version_#x/
-----version_#y/
-----version_#z/

Fedora 20/
-base/
-- patches to steam startup script shipped with distro (like one that already in repo)
-runtime/
-- patches relative to steam runetime (probably not needed)
-steamapp/
-- patches relative to steamapp directories (library entries)
-$appid/
-- patches relative to appid base directory
-----version_#x/
-----version_#y/
-----version_#z/
```

Fixes should also be marked as confirmed or experimental. I would like to see downloading of fixes in an early milestone as we should track releases as close as possible as gamers aren't known for patience ;)

**Comment by boombatower** [comment]
What is the purpose of the `version_#x` under patches? I don't think we want to maintain multiple sets of patches for different game versions. Could possibly guard based on known version, but presumably if an update is released that is not compatible the patch should just be updated.

Currently, the type of fixes are see are flat out bugs, like no 64 bit detection in startup script (but a conditional), libs shipped that are incompatible with the rest of distro, or missing libs. As such I would expect patches to be distro agnostic, lib removal to be agnostic and harmless for those that do not have a problem, and missing libs to be the part that needs to resolve them per distro to install appropriate system packages.

The "repo" of all these fixes has a few concerns. Having a base directory structure in the tree structure makes a lot of duplicate structures for what I foresee to be little to no difference. If anything perhaps mirror obs builds where single spec file with conditionals can be built for multiple distros. Perhaps skipping the build phase and just interpreting by main script.

If there is any building perhaps having that automated via travisci and publish to different branch or even different repo. I have seen other projects use github as source for package repo where they ended up ddos'ing github with stupid implementation. I'd like to avoid that. Presumably we should be able to access repo over http:// and if not cached/cdn then over githubpages for proper cdn.

We could presumably separate repo/db from main script development repo, but given how pivotal the repo information is to the script they'll probably be best to be developed together.

On security front, travisci can be given secrets in a secure manor such that it could be setup to sign scripts and patches and publish signature into git (may be better to keep that part in separate repo). The script could then easily verify all downloaded information.

I should be able to detect app download/update start at which point fixes can be downloaded simultaneously and applied once app download is complete.

@moozaad Since you mentioned fixing a recent game, could you publish the fixes in a patch form or whatever is closest to what we are talking about so we have a solid example to discuss?

**Comment by boombatower** [comment]
I stubbed out:
- steamtricks_fix_fetch $APPID
- steamtricks_fix_apply $APPID

which are invoked at the appropriate times.

Presumably if the fix_fetch takes longer than update update steamtricks will end up processing the update finish event after it completes download and apply changes then. This works since steamtricks in not multithreaded!

Those function should give us the appropriate place to download fix information from repo and apply.

Application of patches should probably check if patch --reverse with dry-run works (perhaps use git apply) and if already applied do not bother. That way failed application can be detected apart from already applied since updates may not touch all files.

**Comment by boombatower** [comment]
Another thought related to patches.

Provide simple ordering like udev based on file name.
- 10_first.patch
- 20_second.patch

Always start at 10 and use 10 spacing to allow for adding patches in between.

**Comment by boombatower** [comment]
Also found a solid resource to review to get an idea of the types of issues to be solved.

https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting

**Comment by boombatower** [comment]
So far I am thinking in each app directory::

- incompatible_files: in format `find` is happy with
- 10_first.patch (etc): apply patches in order
- post_script: script to run after find and patch

Could also combine meta information into single file with variables and eval/source it.

A possible workflow for something like Multiwinia becomes:

- incompatible_files: run_steam.sh
- 10_run_steam.patch:
```diff
--- /dev/null	2016-10-03 15:49:25.537737213 -0500
+++ run_steam.sh	2016-10-03 23:47:05.851925857 -0500
@@ -0,0 +1,2 @@
+#!/bin/bash
+./multiwinia.bin.x86
```

Could also patch the file out, but in the case seems less brittle to just remove add back since trying to replace the entire file.

Side note: The script could check for `.git` directory to determine local dev copy and search filesystem relative to itself for repo rather than looking for remote. Could also be variable set at the top of file.

**Comment by boombatower** [comment]
Another thought, if we allow updating the fixes repo on the fly we'll probably need to update steamtricks main script as well. Otherwise, we may not support fixes that require new features (or restricts us from adding new fix features [maybe ok if we get it right]).

As such it may make sense to structure this just like steam with a launcher script that spits out the real script into home and from there it self updates. This somewhat sounds bad since it voids the dependency management systems of Linux and somewhat begs why not package the fixes repo in a separate package and just update it. Obviously, the only real downside is rate at which it can be updated.

One interesting possibility, since it should be complete standalone (not requiring a patch to steam or anything like main script), is that we package on obs for all distros it supports. This could also work for main script, but people will need to either patch steam or start steamtricks manually. As a final options, perhaps we only request that distros package steam with the patch that looks for steamtricks, but does not require it and then we package script and repo separately in a repo we can update as frequently as possible. The proper repo approach means we can use the existing signing and download mechanisms without writing any of that which makes it attractive to me.

**Comment by boombatower** [comment]
Should also decide on making `git apply` a dependency over `patch` since it supports binary patching, file moves, etc which will probably be handy, but doubtful a typical gaming box with have git.

**Comment by boombatower** [comment]
I published a prototype of what I threw out. It does nothing for missing dependencies. I'd like to either depend on tools to do the mapping plus possibly a global list of common ones and fallback to app specifics list or commands in `post/pre` scripts. We'll need to determine a standard way of prompting user to install deps.

I am open to complete overhaul, but figured I'd get something to look at.

Another interesting thought, what if we packaged each app specific fix as a separate package and did the translation of deps at that stage. Then if we build against multiple versions of a distro and such we can utilize obs to tell us when a package is not available and such.

**Comment by boombatower** [comment]
Could also rework multiwinia example to just cp the replacement file over the original, but patches have some merit.

**Comment by moozaad** [comment]
Dawn of war 2 retrib was my example the other day, it needed 3 types of fix to get work (though may not be the optimal solution as the root cause was likely not tackled)

1) TW was missing libpng12_0 and librtmp (not in offical repos - would need to package this up in the same repos as this package). Arch user's reported various SDL deps missing [too.](https://www.reddit.com/r/linux_gaming/comments/551xx5/warhammer_40000_dawn_of_war_ii_chaos_rising_and/)

2) librtmp had the wrong librtmp.so.x, packages had 1 but game wanted 0. A symlink fixed it, thankfully compatible ABI.

3) run script was edited to bypass launching via steam (6 lines commented out) and instead launched directly. I feel that there was more with this that could be fixed but I didn't explore it as the game was working.


Versioning within games is important - there's lots of use cases for not always running the main line in steam and if there are steamtrick patch differences we should accommodate that. We can probably use "buildid" in the appmanifest and operate on ranges of that number (eg. *, 0-31221,>31221). Most games won't need it and can just have a universal fix.


There's a lot of ideas in here and the other threads. They'll need condensing into a roadmap or plan doc and we still need to sit down and have a meeting because I'm throwing ideas about but I'm not really involved yet. How are we handling obs; Home subproject->game:tools or something different?


After looking at the data dir, I would now suggest we go with "$appid-game name" to make it more human friendly and use the dash as a delimiter. We know all appid are integers so we search for ^_$appid_- .*$. It'll make dev & maintenance easier.

I'm currently looking at fixes for starmade (that one is elusive, no sound with openal) and shroud of the avatar (crash after 30s but runs fine directly, devs are also looking at it). 

Also poking Overlord 2 - it runs.... but their input hanlding code is the worst. No easy fix - do we include advisories for known issues that we can't fix? Basically,  if you move the mouse too much the camera will end up spinning for several seconds as it catches up with the new x,y.

**Comment by boombatower** [comment]
Some solid points.

The need to package missing libraries seems to be another good indication for using obs as delivery mechanism since we don't want to reinvent building and deploying libraries. Given that games will need that and that links us to dependency management system it seems to confirm that we just utilize it for the fixes repo as well (at least for now).

The point about running older versions makes sense and we should definitely offer some simple range syntax. The manifest is already parsed and the build id available so that shouldn't be hard to evaluate. Seems like another indicator for base simple directory/file structure with expandable and more specific methods available when necessary rather than always required.

Definitely a lot of good ideas that we should condense and ensure we can design something that accommodates them. Send me something on steam/irc/email (in git log)  and we can setup a time to talk.

For now, lets use a home repo until we have things firmly figured out and can seek a more proper home. We'll most likely want a standalone project due to all the odd deps, rapid updates, and multiple distro builds.

"$appid-game name" is a good suggestion. We can enforce the name matches the way it is presented in manifest, but I am not sure that will be helpful short of perhaps enforcing consistency.

The more I think about it the fix repo is going to be a rapid changing "mess" so I think it will probably be best to make a `steamtricks/steamtricks-data` repo or somesuch so they are entirely separate. For now, lets not worry about having -data repo depend on some version of main repo as we'll just assume one is using latest of both until we stabilize things.

My preference would be to continue with what we have and flesh out so we can provide a fix for Dawn of war 2, since it seems fairly involved, and then call that a first release. At that point if we are confident in stability lets submit SR to have the openSUSE steam package utilize steamtricks which should give us a wider user-base as well. Additionally, we could look at posting around in forums were these fixes are to try and attack people to help automate them in -data repo. Perhaps phoronix would be interested.

Having the automated tests at this point to a) detect games that need work, b) detect game updates or distro updates that break things would be great.

**Comment by boombatower** [comment]
I went ahead and rebuilt my [steamtricks obs repo](https://build.opensuse.org/project/show/home:boombatower:steamtricks) for the new structure. For now it will include steam, but that is until openSUSE accepts the patch. After that I would expect distros to ship steam with patch that optionally loads steamtricks and we'll leave packaging steam to them.

The steamtricks and streamtricks-data packages are about a simple as a package can get which should make supporting many distros quite easy. Obviously, we'll need to port the setup for debian based packages, but it should be simple enough. For now I've included Fedora 24 just to demo the point.

**Comment by boombatower** [comment]
If we do the packages to manage deps, then should probably have a build step that turns dep lists into rpm and deb packages or something along those lines.

**Comment by boombatower** [comment]
We could also skip building packages for the time being and just include lists and issue package management commands to install them.

**Comment by moozaad** [comment]
I'd prefer the patch versions to be the other way around so that 0 is global (eg. >=0), 100 is >=100, etc. Seems more logical to me.

The packages for fixes idea is certainly interesting and I like how neat it would make things. It could also be extended to steam://install/<appid> & remove, if we wanted to provide an interface for such things.

The OBS docs are pretty bad IMHO, certainly ask in #opensuse-buildservice as the devs live there and are super helpful.

GH wiki pages would be suffice for plans and docs for now.

**Comment by boombatower** [comment]
Your change to revision dir approach makes sense. The basic stuff is script so we just need to knock out these last bits.

**Comment by boombatower** [comment]
I am somewhat wondering if the deps are not easier than we are thinking. Kinda like your original question about using ldd. When compiled packages are built the rpm tools end up figuring out the deps automatically and add them to the package requires, but they are not package names rather libs.

For instance, my openage package has the following deps (partial list):
```
libQt5Quick.so.5(Qt_5)(64bit)
libSDL2-2.0.so.0()(64bit)
libSDL2_image-2.0.so.0()(64bit)
```

If one runs:
```
zypper search --provides 'libQt5Quick.so.5(Qt_5)(64bit)'
result: libQtQuick5
```

Similarly, 
```
ldd FORCED.x86_64
libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007f156122a000)
libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f1561027000
```

If I translate that as rpm does into:
```
libxcb-sync.so.1()(64bit)
result: libxcb-sync1
```

As such it seems like we either automatically (perhaps save that for later), or manually make those non-package, but rather lib deps and those should build into obs packages or package management commands.

For instance,
```
zypper in -C 'libxcb-sync.so.1()(64bit)'
```
works as expected.

The other thought I had been having, if we come up with a list of all deps needed by any game (just a big general list) and include all those as build deps...then simply run the same command rpm uses we should get all the deps matched and everything.

For now, I think I'll play with building packages from ldd output and what not and if that doesn't merit much usefulness quickly I may just build some rudimentary package management integration.

**Comment by boombatower** [comment]
Sounds like that's exactly how it works http://www.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html.

- `*.so` files are added to capabilities
- ldd used to determine required capabilities

Alright, so this is relatively easy then. A quick google search indicates that debian package do not have capabilities!? Oh god. Well if that ends up being true I suggest we start with what we use and easy and others can contribute for what they use.

**Comment by boombatower** [comment]
Sweetness, modifying their example script to include arch.

```bash
#!/bin/sh

ulimit -c 0

filelist=`xargs -r file | fgrep executable | cut -d: -f1`

for f in $filelist; do
  arch=$(file $f | cut -d' ' -f3 | sed 's/-//')
  ldd $f | awk '/=>/ { print $1"('$arch')" }'
done | sort -u | xargs -r -n 1 basename | sort -u
```
and passing

```
FORCED.x86
FORCED.x86_64
```
returns
```
libc.so.6(32bit)
libc.so.6(64bit)
libdl.so.2(32bit)
libdl.so.2(64bit)
libdrm.so.2(32bit)
libdrm.so.2(64bit)
libexpat.so.1(32bit)
libexpat.so.1(64bit)
libgcc_s.so.1(32bit)
libgcc_s.so.1(64bit)
libglapi.so.0(32bit)
libglapi.so.0(64bit)
libGL.so.1(32bit)
libGL.so.1(64bit)
libm.so.6(32bit)
libm.so.6(64bit)
libpthread.so.0(32bit)
libpthread.so.0(64bit)
librt.so.1(32bit)
librt.so.1(64bit)
libstdc++.so.6(32bit)
libstdc++.so.6(64bit)
libX11.so.6(32bit)
libX11.so.6(64bit)
libX11-xcb.so.1(32bit)
libX11-xcb.so.1(64bit)
libXau.so.6(32bit)
libXau.so.6(64bit)
libxcb-dri2.so.0(32bit)
libxcb-dri2.so.0(64bit)
libxcb-dri3.so.0(32bit)
libxcb-dri3.so.0(64bit)
libxcb-glx.so.0(32bit)
libxcb-glx.so.0(64bit)
libxcb-present.so.0(32bit)
libxcb-present.so.0(64bit)
libxcb.so.1(32bit)
libxcb.so.1(64bit)
libxcb-sync.so.1(32bit)
libxcb-sync.so.1(64bit)
libXcursor.so.1(32bit)
libXcursor.so.1(64bit)
libXdamage.so.1(32bit)
libXdamage.so.1(64bit)
libXext.so.6(32bit)
libXext.so.6(64bit)
libXfixes.so.3(32bit)
libXfixes.so.3(64bit)
libXrandr.so.2(32bit)
libXrandr.so.2(64bit)
libXrender.so.1(32bit)
libXrender.so.1(64bit)
libxshmfence.so.1(32bit)
libxshmfence.so.1(64bit)
libXxf86vm.so.1(32bit)
libXxf86vm.so.1(64bit)
```

**Comment by boombatower** [comment]
After a bunch of grepping (they never like to make this obivously, or maybe I just missed it)...

/usr/lib/rpm/find-requires (which ends up with the following, that does it all!!)
```
/usr/lib/rpm/rpmdeps --requires FORCED.x86
libGL.so.1                                                                                                                                 
libX11.so.6                                                                                                                                
libXcursor.so.1                                                                                                                            
libXrandr.so.2
libc.so.6
libc.so.6(GLIBC_2.0)
libc.so.6(GLIBC_2.1)
libc.so.6(GLIBC_2.1.3)
libc.so.6(GLIBC_2.11)
libc.so.6(GLIBC_2.15)
libc.so.6(GLIBC_2.2)
libc.so.6(GLIBC_2.3)
libc.so.6(GLIBC_2.3.4)
libc.so.6(GLIBC_2.4)
libc.so.6(GLIBC_2.6)
libc.so.6(GLIBC_2.7)
libdl.so.2
libdl.so.2(GLIBC_2.0)
libdl.so.2(GLIBC_2.1)
libgcc_s.so.1
libgcc_s.so.1(GCC_3.0)
libgcc_s.so.1(GCC_3.4)
libgcc_s.so.1(GLIBC_2.0)
libm.so.6
libm.so.6(GLIBC_2.0)
libm.so.6(GLIBC_2.1)
libm.so.6(GLIBC_2.15)
libm.so.6(GLIBC_2.2)
libpthread.so.0
libpthread.so.0(GLIBC_2.0)
libpthread.so.0(GLIBC_2.1)
libpthread.so.0(GLIBC_2.2)
libpthread.so.0(GLIBC_2.3.2)
librt.so.1
librt.so.1(GLIBC_2.2)
libstdc++.so.6
libstdc++.so.6(CXXABI_1.3)
libstdc++.so.6(GLIBCXX_3.4)
libstdc++.so.6(GLIBCXX_3.4.11)
libstdc++.so.6(GLIBCXX_3.4.15)
libstdc++.so.6(GLIBCXX_3.4.9)
rtld(GNU_HASH)
```

```
/usr/lib/rpm/rpmdeps --requires FORCED.x86_64
libGL.so.1()(64bit)
libX11.so.6()(64bit)
libXcursor.so.1()(64bit)
libXrandr.so.2()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.11)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.6)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.4)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.15)(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
rtld(GNU_HASH)
```

**Comment by boombatower** [comment]
Summarized, this seems to suffice. Execute in game directory and rpm does the rest.
```
find . -type f | /usr/lib/rpm/find-requires
```

**Comment by boombatower** [comment]
Master plan to ignore what is shipped with app, we should add script to remove files (already supported) that interfere and run deps last. This avoid zypper looking for libsteam_api.so and what not.

```bash
find . -type f | /usr/lib/rpm/find-provides | sort > provides
find . -type f | /usr/lib/rpm/find-requires | sort > deps
comm -23 deps provides > needed
pkexec zypper -n in -C $(cat needed)
```

Unfortunately, `zypper search --provides $(cat needed)` which does not require root does not differentiate between 32 and 64bit packages so it's not easy to tell (without added logic) if there are missing packages. Preferably, steamtricks could check and only if missing trigger user to install.

**Comment by boombatower** [comment]
Alright, I'm happy with:
```
xdg-terminal 'sudo zypper ref'
```

**Comment by boombatower** [comment]
Alright, that's done. Now just need the revision based directory interpretation and I think that's everything. A few bugs/issues I'm made issues about that would be nice to clear up, but close to a solid release. Then just look for users and folks to fill in data repo.

**Comment by moozaad** [comment]
Okay that sound good but how would that works for example librtmp.so.0 which has no provider? Not only that but the available OBS and packman libs are librtmp.so.1. As you may know, that may mean it has an incompatible ABI.

Would this case but done with a custom script separate to the other deps automagic?

Are we going to package these rare libs on obs for steam tricks (subject to obs blacklists)?

**Comment by boombatower** [comment]
Yeah, rare, non-provided libs will need to be packaged and then the deps check should install them like any other. If there are libs with compatible abi a script should setup a symlink if possible in the game directory and setup ldd to use that lib, alternatively asking use for sudo to make link in system lib dir may be an option.

**Comment by boombatower** [comment]
Since out of context stuff has other issues created and this is done for openSUSE, I'll consider this done for now. Definitely need to reference this issue given the immense amount of thoughts, but just trying to keep track of what needs to be done.
