### ISSUE TITLE
steamtricks data can't be found

### ISSUE THREAD

**Issue by janat08** [steamtricks/steamtricks#41]
I can't find steamtricks data to determine what this does for games in case that it may be causing problems, for example with empire total war which has garbled text on opensuse, or if i can ask it to try and do more specific stuff for this problem.

**Comment by boombatower** [comment]
As in the `steamtricks-data` package on openSUSE? Should be installable just like `steamtricks` same names used for the code repositories on github. Are you trying to create/automate a fix? See the [wiki](https://github.com/steamtricks/steamtricks/wiki) for details on how to do so.

**Comment by janat08** [comment]
No I couldn't determine location of this package to understand what steamtricks did. Previous comment assumed that this is more so a troubleshooting package than a patching one, as it is now very obvius by how it demands attention after every update.

**Comment by boombatower** [comment]
If you know of fixes that can be applied to empire total war feel free to point out what they are (link to forum post or similar) so they can be automated. Otherwise, if looking to use as troubleshooting tool and no longer of interest it probably makes sense to close the issue.
