### ISSUE TITLE
Crashes xwin_x11 for dota on opensuse

### ISSUE THREAD

**Issue by janat08** [steamtricks/steamtricks#45]
If you insist I can provide you my own console output that apparently doesn't do anything in itself.

**Comment by boombatower** [comment]
Some details would be helpful as Dota 2 runs fine on Tumbleweed for me.

**Comment by janat08** [comment]
Yes, it happened twice while I was switching windows back and forth. Last
time it worked.

**Comment by janat08** [comment]
Crashed again with atom open which uses electron while I wasn't switching windows. I also happen to have wayland in my bin directory which isn't terribly reassuring even though it's meant to be a replacement.

**Comment by boombatower** [comment]
This would seem to have little to do with Dota 2 and even less to do with steamtricks. Sounds more like graphics drivers or xwin_x11. Without some real evidence (logs, etc) or steps for reproducing this is not going to go anywhere. The only effects steamtricks will have are on the game launching at all (at least at this point). So if Dota 2 runs and at some point any application seems to cause your desktop environment to crash then you should look elsewhere. I would suggests looking up where X11 logs are and seeing if anything interesting in there.
