### ISSUE TITLE
Dota 2 crashes/steam won't start: file removed

### ISSUE THREAD

**Issue by janat08** [steamtricks/steamtricks#46]
Removes troublesome file on opensuse, steam doesn't show signs of life.

**Comment by boombatower** [comment]
Can you provides the full logs from starting steam from the command line, also try to start Dota (if Steam works) while Steam is running in command line as errors will display there. The system/distro details (and `steamtricks --version`) would be helpful and I assume you attempted to start Steam again as it is finicky when it does a runtime update.

Also you can see [wiki](https://github.com/steamtricks/steamtricks/wiki#reporting-issues) for details on viewing steamtricks logs and what not.

**Comment by janat08** [comment]
no video driver and swarast it says.

**Comment by janat08** [comment]
running tumbleweed, so the drivers don't keep up.

**Comment by boombatower** [comment]
I would recommend discussing in irc.freenode.net#opensuse, the forums, or bugzilla with details on your hardware (run `hwinfo`) and perhaps install `Mesa-demo-x` and dump the output of `glxinfo` there as well.

**Comment by boombatower** [comment]
If you would pastebin the output from `steam` that may also shed some light. I'm in IRC as the same name as well.

**Comment by janat08** [comment]
https://pastebin.com/psEWGqJ3

**Comment by boombatower** [comment]
I do not see steamtricks message in log, is this running without steamtricks? Also `LIBGL_DEBUG=verbose steam` should provide more details on why failing to start. You can run `steam --reset` to start from clean slate.

**Comment by janat08** [comment]
I reinstalled steam, but it says on start up that file was removed by steamtricks. Tried reset.

**Comment by boombatower** [comment]
Steam is rather fickle sometimes, I have an issue for trying to handle the variety of oddities it can have during launch in steamtricks, but have not gotten around to it.

One workaround for DRI3 related issues which yours seems to be is to run the following:

```
LIBGL_DRI3_DISABLE=1 steam
```

Get steam to properly launch, then quit and relaunch normally.

**Comment by janat08** [comment]
yes, ty very much.

**Comment by boombatower** [comment]
I take it worked? Happy to hear.

**Comment by janat08** [comment]
Yes it will restart ok after first lauch.

**Comment by boombatower** [comment]
Cool. Definitely something I would like to have steamtricks handle. If you are interested/capable perhaps you have time to take a look. :)

**Comment by janat08** [comment]
Im javascript person, but perhaps posting notification explaining that it has to be relaunched such a way in liu of interfacing with OS like that would make it much easier?

**Comment by boombatower** [comment]
Yeah, part of the trick is getting access to that error output and the second being creating a set of patterns to match and solutions (or messages) to output. Solving just this case as it seems to be one of the most common would not seem to bad.

Alright, well thanks for the report.
