### ISSUE TITLE
steamtricks still needed

### ISSUE THREAD

**Issue by tomtomme** [steamtricks/steamtricks#48]
Dear Boombatower,
thanks for steamtricks, it helped in some situations in the past. Would you say that it is still needed on an up to date system (opensuse tumbleweed)? Or are the fixes superseeded by upstream work til now?
Thanks, tomtomme

**Comment by boombatower** [comment]
Various games still have issues on TW and similar. Steam itself still has trouble boostrapping on the first run, but I never got around to handling that is it is non-trivial. Depending on what you play you may not need it, but it also doesn't harm anything.

Everything in https://github.com/steamtricks/steamtricks-data/tree/master/data still remain issues it fixes and the generic fixes are still needed for games like Portal 2.
