### ISSUE TITLE
Determine language constraints

### ISSUE THREAD

**Issue by boombatower** [steamtricks/steamtricks#5]
The project could be implemented in a variety or combination of languages, but obviously that will bring in related dependencies when installed. This is an issue for that discussion.

This also affects things like how `vdf` files can be parsed, etc.

Bash is fine and all, but I wouldn't mind something like PHP for a bit more functionality. I've actually written something that does simultaneous log watches and such related to Steam in PHP

**Comment by moozaad** [comment]
I think bash is the optimal choice. Plenty of tools for watching and reacting to changes like inotify. You can even parse xml, sqllite and json in it if you need to. 

PHP is not commonly installed on desktop machines which is my main reason for not wanting to depend on it. Python would be in line first for stuff that's too troublesome in bash as that is readily available but it also depends on what you are fluent in.

Lastly small utils _if needed_ can be done in C/C++ for speed. I like the linux principle of individual tools doing very limit small jobs.

**Comment by boombatower** [comment]
Yeah, sounds fair to start with bash and see how things go.

**Comment by moozaad** [comment]
Guess I'd better brush up on bash then as my strengths are in c/c++/c# and.... php :)

**Comment by boombatower** [comment]
Settled then, and since mostly done it's probably safe to say bash.
